### ISSUE TITLE
Synapse 0.9.x and later remove commandline options which break the dockerfile

### ISSUE THREAD

**Issue by ara4n** [silvio/docker-matrix#1]
Hi Silvio,

In Synapse 0.9.0 we removed most of the commandline parameters for synapse as they were duplicating the main YAML config file which has now become really large/nested/complicated.  To quote the changelog:
- Remove support for specifying config options on the command line, except
  for:
  - `--daemonize` - Daemonize the home server.
  - `--manhole` - Turn on the twisted telnet manhole service on the given
    port.
  - `--database-path` - The path to a sqlite database to use.
  - `--verbose` - The verbosity level.
  - `--log-file` - File to log to.
  - `--log-config` - Python logging config file.
  - `--enable-registration` - Enable registration for new users.

This means that the dockerfile breaks because you preferred commandline args over maintaining a YAML config file.

Let me know if you can fix this or whether we should provide a PR.  Synapse 0.9 is lightyears ahead of where we were back in March btw :)

M

**Comment by silvio** [comment]
thx @ara4n to pointing me. I will resolve this. I update synapse on my server once in a week, but had no issue with this ^^ ... Maybe I have some other issues here.

**Comment by silvio** [comment]
Okay - I think you mean matrix-org/synapse@d624e2a6383bbb179132b79eec80fa516e747bd6
This is just for generating of a yaml file. Configured systems are fine at now. Only new systems have this problem.

@ara4n I see two solutions here.
- I provide a templatefile which I have to change to the values which fits for the user.
- synapse drops completly the `--generate-config` thing and put a templatefile in his repo, because the current implementation isn't useful for anything. The user must edit the file for his needs.

The first option is error prone, because synapse is under heavy development and the expected values sooner or later are not in my templatefile.

What do you think?

**Comment by ara4n** [comment]
Yup, this is the commit in question.  Why not just run --generate-config in the dockerfile in order to generate the YAML with the appropriate hostname etc?  I'm not sure what the difference is between us shipping a YAML template config file and programmatically creating one?  One can always s/// (or apply YAML transforms) to the output of --generate-config?

@leonerd - this may also be relevant to your config mangling for debian packages?

@negativemjark - what do you think about the pros & cons of just shipping a template YAML rather than ---generate-config?

**Comment by leonerd** [comment]
`--generate-config` does more than just generate a config file though. It also creates all the crypto keys.

I'd be much in favour of splitting that out to its own separately-callable action that the debian package could run at `postinst` time if required, but stick to a templated config file the then the debian package can just ship pre-filled in with filesystem locations.

**Comment by silvio** [comment]
I have reviewed a little bit was is going on.
Before the commit I could add all pathes to my generate config script and all settings are okay with the internal pathes of the docker image. (Docker mounts a host folder to an internal docker containers folder `/data`)
After this commit some pathes (`pid_file`, `log_file`, `media_store_path`, `database`) are wrong and some are okay (`tls_certificate_path`, `tls_private_key_path`, `tls_dh_params_path`, `log_config`, `signing_key_path`).
I think the mentioned commit was not complete. All this pathes need the same prefix. Without this I have to handle this in the `readme.md` file.

**Comment by ara4n** [comment]
@negativemjark - i think you're best positioned to answer this one...

**Comment by NegativeMjark** [comment]
It sounds like the problem is that synapse --generate-config defaults to using the current directory for data store paths. But defaults to the where the config file is stored for certificate files. This behaviour has been present since matrix-org/synapse@5da65085d106e98cf7b762836cb300d01226bf92 . For now it should be possible to get the right directory by changing to the /data directory before running --generate-config.

If it would be useful to have explicit --data-prefix and --config-prefix options for synapse --generate-config then that should be fairly easy options for us to add.

**Comment by silvio** [comment]
@NegativeMjark thx for pointing me to the workaround. `--data-prefix` and `--config-prefix` would be nice to have.

I will fix this issue with the workaround for now.

**Comment by silvio** [comment]
With commit 12fbe64c122e0a1ca5d917f3df3e56e084ced451 it should be closed.
