### ISSUE TITLE
Invalid network setup

### ISSUE THREAD

**Issue by maxidorius** [silvio/docker-matrix#36]
You only expose port 8448 and recommend to change the self-signed certificate but it has been established in matrix-org/synapse#2438 that this is not the recommended setup.

Port 8448 and 8008 should be exposed, with a reverse proxy on 8008

**Comment by joenas** [comment]
Maybe add something about using `-p 127.0.0.1:8008:8008` when reverse proxying so the port isn't accessible outside the host.

**Comment by maxidorius** [comment]
@joenas it should be, or how do you see the reverse proxy connecting to it? there shouldn't be an assumption that it is on the same host.

**Comment by joenas** [comment]
Well if it isn't on the same host it's a different matter of course. But if it is it seems like a bad idea to expose it?

**Comment by maxidorius** [comment]
To expose it publicly, sure, but on a container host which is usually not directly exposed to internet wihtout any kind of firewalling or NAT, it would seems very unlikely. But up to @silvio.
I know it would be a pain for most users tho.

**Comment by joenas** [comment]
Ah well I just recently learned that if you use `-p 8008:8008` then `docker` will add that port to `iptables` and depending on what firewall you have that will override, unless you specifically tell `docker` to only expose on `localhost`. I use `ufw` which isn't the most advanced firewall of course but running a container host which is exposed to the public internet if you're a hobbyist doesn't seem that unlikely to me. Because that's what I do :)

**Comment by andreaspeters** [comment]
I add the new information into the readme. thanks for it. :-)
