### ISSUE TITLE
Error when I try to build docker image

### ISSUE THREAD

**Issue by geosphere** [silvio/docker-matrix#64]
Cloned after #63 and ...  

```
+ pip install --upgrade pip
Collecting pip
  Downloading pip-10.0.0-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-10.0.0
+ pip install --upgrade wheel
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

```

**Comment by mvgorcum** [comment]
I can confirm this.
If you comment out `pip install --upgrade pip` it will work fine, though.

I'll have to take a look to find out why updating pip causes this error.

[edit] As it turns out, pip 10.0.0 was just released which apparently breaks the dockerfile. Removing the pip upgrade is a workaround for now.

**Comment by andreaspeters** [comment]
It looks like a failure of pip byself. For the first, we will take out the update line.

**Comment by andreaspeters** [comment]
In the main repo is the update line already out (https://github.com/AVENTER-UG/docker-matrix). The pipeline to update the docker images is running. thanks for open the ticket. :-)
